### PR TITLE
Added dynamic configuration of the .pdf metadata with hyperref

### PR DESCRIPTION
**Pull request by danielvcorreia**
Since it is not possible to use the fields (author's name, thesis title, etc.) in the matter.tex file (from the cover.tex file), this was the best solution I found to go around that problem.

The alternative was for each template user to change the .pdf metadata parameters to their own. Is that a better solution?

### CODE REVIEW

**Comment by jpbarraca** [comment]
There is an ongoing discussion with the University regarding the inclusion of metadata in the final PDF. Besides the fields you identify, it should also consider a clean version of the abstract.

Regarding your PR, why don't we change the definition of the original macros in order to define the correct values for hyperref, or to create a temporary file which can be used by matter.tex or the Makefile.

**Comment by jpbarraca** [comment]
The `cover.tex` file is already very simple, allowing students to define simple variables which are later used. This colides with the `fields.txt` file you propose and may introduce further confusion.

If another file is required, why not using `\write` to create it without increasing the complexity for users?

**Comment by danielvcorreia** [comment]
I can write the variables to a temporary file, but I'm having trouble reading the variables in the preamble of the `cover.tex` file... It occurs an Emergency stop with the error: 
> (cannot \read from terminal in nonstop modes)

**Comment by danielvcorreia** [comment]
The current implementation uses a temporary file to store the information used in the file metadata. It no longer uses the `fields.tex` file to store that information.

A warning occurred when `\\` was used in the metadata parameters, so I changed the `\Author` command.

Regarding the clean version of the abstract. The current abstract example also uses `\\` (warning occurs), and commands like `\selectlanguage` and `\begin{itemize}` that originate errors. How do I approach this situation? Should I change the example, or is there a way to clean the text from such commands?

**Comment by danielvcorreia** [comment]
(I don't know if my previous comment was read)

The current implementation works and uses a temporary file.

I don't know how to approach this:
> Regarding the clean version of the abstract. The current abstract example also uses \\ (warning occurs), and commands like \selectlanguage and \begin{itemize} that originate errors. How do I approach this situation? Should I change the example, or is there a way to clean the text from such commands?

@jpbarraca

**Comment by jpbarraca** [comment]
Please check #56 which may facilitate this PR.

**Comment by jpbarraca** [comment]
When using the work from the branch referenced in #56 we do not need intermediate files, as all the information is available. Can you check it?

**Pull request closed without merging**
